'use strict';
var Promise;

Promise = require('pinkie-promise');

module.exports = function() {
  var args, callbackHandle, fn, reject, resolve;
  args = Array.prototype.slice.call(arguments);
  fn = args.shift();
  resolve = null;
  reject = null;
  callbackHandle = function() {
    var err;
    args = Array.prototype.slice.call(arguments);
    err = args.shift();
    if (err) {
      return reject(err);
    } else {
      return resolve.apply(null, args);
    }
  };
  args.push(callbackHandle);
  return new Promise(function(resolvePromise, rejectPromise) {
    resolve = resolvePromise;
    reject = rejectPromise;
    return fn.apply(null, args);
  });
};

// ---
// generated by coffee-script 1.9.2
